project:
  type: website
  output-dir: "."

website:
  title: "Portfólio Jhonatan"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: about.qmd
        text: About
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/atanaziojhonatan/?jobid=1234"

format:
  html:
    theme: cosmo
    css: styles.css



